version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 6
  complex-logic:
    enabled: true
    config:
      threshold: 6
  file-lines:
    enabled: true
    config:
      threshold: 300
  method-complexity:
    enabled: true
    config:
      threshold: 7
  method-count:
    enabled: true
    config:
      threshold: 25
  method-lines:
    enabled: true
    config:
      threshold: 35
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: 95
  identical-code:
    enabled: true
    config:
      threshold: 57
  sonar-java:
    enabled: true
    config:
      sonar.java.source: "11"
      test_patterns:
        - src/test/**
      rules:
        - "java-basic"
        - "java-design"
plugins:
  fixme:
    enabled: true
  sonar-java:
    enabled: true
    config:
      sonar.java.source: "11"
  checkstyle:
    enabled: true
  pmd:
    enabled: true

exclude_patterns:
- "config/"
- "db-design/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "**/vendor/"
- "**/*.d.ts"
