INSERT INTO DEBS.ACCOUNT(NAME,DESCRIPTION,PARENT_ID,ACCOUNT_TYPE) VALUES('Cash','Cash desc',0,1);
INSERT INTO DEBS.ACCOUNT(NAME,DESCRIPTION,PARENT_ID,ACCOUNT_TYPE) VALUES('Fuel','Fuel desc',0,2);

INSERT INTO DEBS.ENTRY(AMOUNT,ETYPE,ACCOUNT_ID) VALUES(-1000.00,1,1);
INSERT INTO DEBS.ENTRY(AMOUNT,ETYPE,ACCOUNT_ID) VALUES(1000.00,2,2);
INSERT INTO DEBS.TRANSACTION(REFERENCE,NARRATIVE,EID_FROM,EID_TO) VALUES('Ref 1','Nar 1'1,2);

SELECT TX.ID,TX.CREATED,TX.DELETED,TX.REFERENCE,TX.NARRATIVE,TX.EID_FROM,TX.EID_TO,
FE.ID AS "FROM_ID",FE.AMOUNT AS "FROM_AMOUNT",FE.ETYPE AS "FROM_TYPE",FE.ACCOUNT_ID AS "FROM_ACCOUNT_ID",
TE.ID AS "TO_ID",TE.AMOUNT AS "TO_AMOUNT",TE.ETYPE AS "TO_TYPE",TE.ACCOUNT_ID AS "TO_ACCOUNT_ID"
 FROM DEBS.TRANSACTION AS TX
 INNER JOIN DEBS.ENTRY AS FE ON FE.ID=TX.EID_FROM AND FE.ETYPE=1
 INNER JOIN DEBS.ENTRY AS TE ON TE.ID=TX.EID_TO AND TE.ETYPE=2;
