DROP TABLE IF EXISTS DEBS.ACCOUNT;

CREATE SCHEMA IF NOT EXISTS DEBS;

CREATE TABLE IF NOT EXISTS DEBS.ACCOUNT (
  ID IDENTITY GENERATED ALWAYS AS IDENTITY,
  CREATED SMALLDATETIME NOT NULL DEFAULT(CURRENT_TIMESTAMP()),
  BALANCE DECIMAL NOT NULL DEFAULT(0.00),
  DELETED BOOLEAN NOT NULL DEFAULT(FALSE),
  NAME VARCHAR(50) UNIQUE NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  PARENT_ID BIGINT NOT NULL,
  ACCOUNT_TYPE INT CHECK(ACCOUNT_TYPE >= 1 AND ACCOUNT_TYPE <= 8)
);

-- Balance: 1
INSERT INTO DEBS.ACCOUNT(NAME,DESCRIPTION,PARENT_ID,ACCOUNT_TYPE) VALUES('Balance', 'Build-In',0,8);
-- Net Worth: 2
INSERT INTO DEBS.ACCOUNT(NAME,DESCRIPTION,PARENT_ID,ACCOUNT_TYPE) VALUES('Net Worth', 'Build-In',1,8);
-- Assets: 3
INSERT INTO DEBS.ACCOUNT(NAME,DESCRIPTION,PARENT_ID,ACCOUNT_TYPE) VALUES('Assets', 'Build-In',2,8);
-- Liabilities: 4
INSERT INTO DEBS.ACCOUNT(NAME,DESCRIPTION,PARENT_ID,ACCOUNT_TYPE) VALUES('Liabilities', 'Build-In',2,8);
-- Income & Liabilities: 5
INSERT INTO DEBS.ACCOUNT(NAME,DESCRIPTION,PARENT_ID,ACCOUNT_TYPE) VALUES('Income & Liabilities', 'Build-In',1,8);
-- Income: 6
INSERT INTO DEBS.ACCOUNT(NAME,DESCRIPTION,PARENT_ID,ACCOUNT_TYPE) VALUES('Income', 'Build-In',5,8);
-- Expenses: 7
INSERT INTO DEBS.ACCOUNT(NAME,DESCRIPTION,PARENT_ID,ACCOUNT_TYPE) VALUES('Expenses', 'Build-In',5,8);
-- Opening Balance: 8
INSERT INTO DEBS.ACCOUNT(NAME,DESCRIPTION,PARENT_ID,ACCOUNT_TYPE) VALUES('Opening Balance', 'Build-In',1,6);
