DROP TABLE IF EXISTS DEBS.ACCOUNT;

CREATE SCHEMA IF NOT EXISTS DEBS;

CREATE TABLE IF NOT EXISTS DEBS.ACCOUNT (
  ID IDENTITY GENERATED ALWAYS AS IDENTITY,
  CREATED SMALLDATETIME NOT NULL DEFAULT(CURRENT_TIMESTAMP()),
  BALANCE DECIMAL NOT NULL DEFAULT(0.00),
  DELETED BOOLEAN NOT NULL DEFAULT(FALSE),
  NAME VARCHAR(50) UNIQUE NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  PARENT_ID BIGINT NOT NULL,
  ACCOUNT_TYPE INT CHECK(ACCOUNT_TYPE >= 1 AND ACCOUNT_TYPE <= 8)
);

INSERT INTO DEBS.ACCOUNT(NAME,DESCRIPTION,PARENT_ID,ACCOUNT_TYPE) VALUES('Balance', 'Build-In',0,8);
